### ISSUE TITLE
Windows Build Issues

### ISSUE THREAD

**Issue by cschmitt-r7** [libyal/libevtx#1]
Hi,

I'm trying to get a build compiled on Windows 7 x64 w/ VS 2013 but it seems to be bombing out when building `libcthreads` throwing...

```
1>------ Build started: Project: libcthreads, Configuration: Release Win32 ------
1>  libcthreads_thread_pool.c
1>..\..\libcthreads\libcthreads_thread_pool.c(44): fatal error C1189: #error :  TP_POOL support not implemented yet
========== Build: 0 succeeded, 1 failed, 10 up-to-date, 0 skipped ==========
```

I noticed it said multi-threading support is planned? Is there a way to disable the Thread Pool?

**Comment by cschmitt-r7** [comment]
I dropped down to Visual Studio 2010 and was able to get some builds.

**Comment by joachimmetz** [comment]
>  noticed it said multi-threading support is planned? Is there a way to disable the Thread Pool?

In https://github.com/libyal/libevtx/blob/master/common/config_winapi.h#L26
you can set WINVER accordingly e.g. WINVER=6.0 (Vista and later)

TP_POOL support is for Windows 8.0 (WINVER=6.2) and later; and has not been implemented yet.
https://github.com/libyal/libcthreads/blob/bb8489d16fbcde5b574c9b6549e85c8d027f5865/libcthreads/libcthreads_thread_pool.c#L44
