### ISSUE TITLE
Unable to make due to changes in libfvalue

### ISSUE THREAD

**Issue by gclen** [libyal/libevtx#14]
Hi,

When I download the latest source distribution and run

> ./synclibs.sh
> ./autogen.sh
> ./configure
> make

I get the following error:

> In file included from libfwevt_xml_tag.h:31:0,
>                  from libfwevt_xml_document.h:32,
>                  from libfwevt_template.c:35:
> libfwevt_libfvalue.h:35:36: fatal error: libfvalue_split_string.h: No such file or directory
> compilation terminated.

It looks like this is caused by [this commit to libfvalue](https://github.com/libyal/libfvalue/commit/cd3efd41daf7f75da6de295d7f65f6128fdbfabc). Is the API the same in libfvalue (other than being split into two files)? Can I just update the include statements to the two files or are there other changes that need to be made? Thanks for creating such a useful library!

**Comment by joachimmetz** [comment]
Thx for letting me know. CI tests had pointed out the issue as well: https://travis-ci.org/libyal/libevtx/jobs/332150331 but I did not have the time yet to provide a fix.

**Comment by gclen** [comment]
Thanks for the fix!

**Comment by joachimmetz** [comment]
For context this was fixed in https://github.com/libyal/libevtx/commit/c2e61a447b56df043d186d22dec4bf697c6a9ecf
