### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by citronneur** [libyal/libevtx#22]
Hi,

First thanks a lot for libyal.
I would like to ask you if you are interesting in a PR that add support for CMake?

Thanks

**Comment by joachimmetz** [comment]
> I would like to ask you if you are interesting in a PR that add support for CMake?

Could you highlight what benefits you think this has above the current solution?

Note that this is a change that would to be needed deployed libyal wide. Just updating libevtx unfortunately makes the maintenance burden higher by introducing yet another technology.

**Comment by citronneur** [comment]
CMake is easier for Windows developper, you don't need to update your sln file for each version of visual studio or SDK.

You can use the ExternalProject_Add module of cmake to manage your external dependencies if all libyal support CMake indeed. And all cmake based project can use libevtx transparently through [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html) (this is my case ;-))

At the end you can generate all your packaging (rpm, deb, or what you want) thanks to CMake.

First step could be what [protobuf](https://github.com/protocolbuffers/protobuf/tree/master/cmake) project done, i mean create a cmake folder a the root of libevtx project that encompass all your cmake rules, that can be used separatly for cmake user.

I can easily propose you a PR.

Thanks for reply.

Thank again for your work, I really enjoy your work on libyal ;-)

**Comment by joachimmetz** [comment]
you can always send/propose a PR, just note I might not ending up merging it until all build/deployment questions have been addressed

Note that the Makefile.am files of the libyal dependencies are generated by synclibs.sh
Also CMake will need to work with setup.py to create an hermetic Python binding so or DLL

**Comment by joachimmetz** [comment]
No update from original reporter closing issue
