### ISSUE TITLE
Link to Token types does not work on Github?

### ISSUE THREAD

**Issue by WHK102** [libyal/libevtx#25]
In the  `libevtx/documentation/Windows XML Event Log (EVTX).asciidoc` file, the link of `Token types` is dead.

Replace `#token_type` to `#token-types`.

**Comment by joachimmetz** [comment]
This is due to how Github renders asciidoc, the document just contains an asciidoc reference

**Comment by joachimmetz** [comment]
Changes to references in https://github.com/libyal/libevtx/commit/910be7932ebdeec8aeef4f13176173d3ee6f37b7, closing issue
