### ISSUE TITLE
libfwevt_xml_document_read_element: invalid template value size value out of bounds.

### ISSUE THREAD

**Issue by vizmur** [libyal/libevtx#31]
I am trying to export evtx information from the log files, but I get below error. EVTX files are opening without any problem in Windows EventViewer. **evtxinfo** is working fine too, and displays number of records correctly.

Error I get is below.

**Unable to export file.**
libfwevt_xml_document_read_element: invalid template value size value out of bounds.

**Comment by joachimmetz** [comment]
which version?

**Comment by joachimmetz** [comment]
In-actionable without additional context, closing.
