### ISSUE TITLE
Additional python record properties

### ISSUE THREAD

**Issue by pukhanov** [libyal/libevtx#8]
Would be it possible to add a method and descriptor to the pyevtx record for Channel?

**Comment by joachimmetz** [comment]
> Would be it possible to add a method and descriptor to the pyevtx record for Channel?

Yes this would be possible. I mean that you would like to see this functionality added I'll have a look when time permits or feel free to send me a PR.

**Comment by joachimmetz** [comment]
Added in https://github.com/libyal/libevtx/commit/d028b4f90886d467b2960b69084aa2485d7e218b
